name: Deploy

permissions:
  contents: read

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ cms_publish_trigger ]

jobs:
  deploy:
    name: Trigger deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: |
          curl -X POST ${{ secrets.DEPLOY_URL_MAIN }}
